[package]
name = "udev-hid-bpf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libbpf-rs = "0.17"
udev =  { version = "^0.6.3", features = ["mio08"] }
mio = { version = "0.8", features = ["os-ext"] }
glob = "0.3"

[build-dependencies]
libbpf-cargo = "0.11"
