[package]
name = "udev-hid-bpf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libbpf-rs = "0.20"
libbpf-sys = "^1.1.0"
udev =  { version = "^0.6.3", features = ["mio08"] }
mio = { version = "0.8", features = ["os-ext"] }
globset = "0.4"
libc = "0.2"
clap = { version = "4.2.1", features = ["derive"] }
log = "0.4"
stderrlog = "0.5"
errno = "0.3.3"

[build-dependencies]
libbpf-cargo = { version = "0.20" }
bindgen = "0.66.1"
regex = "1.9.1"
